version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -v -ldflags '{{.LDFLAGS}}'

vars:
  PROJECT_NAME: "dummy-discovery"
  DIST_DIR: "dist"
  VERSION:
    sh: echo "$(git describe --tags --dirty --broken)"
  TIMESTAMP:
    sh: echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  LDFLAGS: >
    -X github.com/arduino/dummy-discovery/version.Tag={{.VERSION}}
    -X github.com/arduino/dummy-discovery/version.Timestamp={{.TIMESTAMP}}
