version: "3"

tasks:
  build-dummy-discovery:
    desc: Build the dummy-discovery client example
    cmds:
      - go build -o dist/dummy-discovery -v -ldflags '{{.LDFLAGS}}' ./dummy-discovery

vars:
  PROJECT_NAME: "dummy-discovery"
  DIST_DIR: "dist"
  VERSION:
    sh: echo "$(git describe --tags --dirty --broken)"
  TIMESTAMP:
    sh: echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  LDFLAGS: >
    -X github.com/arduino/pluggable-discovery-protocol-handler/dummy-discovery/args.Tag={{.VERSION}}
    -X github.com/arduino/pluggable-discovery-protocol-handler/dummy-discovery/args.Timestamp={{.TIMESTAMP}}
